apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: eW91cl9yb290X3Bhc3N3b3Jk  # base64-encoded "your_root_password"
  MYSQL_DATABASE: eW91cl9kYXRhYmFzZV9uYW1l  # base64-encoded "your_database_name"
  MYSQL_USER: eW91cl91c2VybmFtZQ==  # base64-encoded "your_username"
  MYSQL_PASSWORD: eW91cl9wYXNzd29yZA==  # base64-encoded "your_password"

