

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./php:/var/www/html

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    env_file: ./.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

